### ISSUE TITLE
Milestone device connection due

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#104]
Device connection milestone due to 31.01.2014 23:59 UTC + 01:00

**Comment by geht** [comment]
@RockItDown 
the first deadline was Tue 28.01.2014. I moved the deadline to the 31.01. because you obviously weren't finished by tuesday. I still see a bunch of open issues now and no commits at all. I would like to have a status report on how far you are now, on what you have done for this task until now, as well as an explanation why you are not finished yet and estimation on when you will be finished with this task. Long story short, please explain yourself!

**Comment by RockItDown** [comment]
I encountered some problems on the player side communication, because it is using at and c++ I needed some time to read into some literature. I already finished c# editor side communication(including broadcasting for device detection). But could not test it yet. So there are no commits to the master yet made. I almost finished with the c++ part for sending the peoject by know, too. So I think if I do not encounter to many problems during testing I'm finished at 2.February.

**Comment by geht** [comment]
@RockItDown 
I still can't see any of your progress here...
the c# part should at least have been in your own branch here on github by now!
Until now you still have not commited a thing! Neither here, nor in the player project.

Your task now:

Upload the stuff you have done until now ASAP!
The C# goes in your public branch here in this project.
The C++ player part goes in your public branch in the player project.
This is so we can see some of your progress.
After that get your task done! it should have been finished by last tuesday!

Let me be clear. This is nothing personal but
if your stuff isn't up by tomorrow 18:00 I will have to notify Matthias and Till about your work attitude!

additional, i hope i don't have to remind you that this task is not the only one you have to get done until our next meeting...

**Comment by RockItDown** [comment]
I am sorry for the inconvenience.
I uploaded the requested data.
I know that my work attitude is a problem, and i will work on it 
in order o get more things done.

**Comment by geht** [comment]
the c++ part is still not up...
just a short reminder, the device connection shall work by 18:00!

**Comment by RockItDown** [comment]
Its up, i forked the repository because the addational functions are not needed, Ehen used locally

**Comment by geht** [comment]
> i forked the repository because the addational functions are not needed, Ehen used locally

you forked the player? I can't see it. Have you already made it public?
And there are still open issues, as i said before, the device connection shall work by 18:00, meaning that the milestone should be finished by then.

**Comment by RockItDown** [comment]
I have not payed for an contract so I'm quite shure that it is public

**Comment by geht** [comment]
the player has only got one contributor (Firebusa)
there is no branch of yours up there...

**Comment by RockItDown** [comment]
https://github.com/RockItDown/ARdevKitPlayer

**Comment by RockItDown** [comment]
I still have to do some Debugging and a nice pop up input window for the editor. How is the situation?

**Comment by geht** [comment]
well... keep it up!
get your stuff stable and compilable so that you can merge to the master.
there should be a new player executable as well...

Bastel halt die Grundfunktion mit ins EditorWindow rein, sodass man mal was vom Editor zum Player schicken kann. (und stell uns natürlich auch mal ne kompilierte Version vom neuen Player zur Verfügung)
Du weißt doch, was du zu tun hast.
Sieh halt zu, dass du das Zeug für deinen Milestone fertig kriegst.

Du hattest mittlerweile über zwei Wochen Zeit um diese Funktionalitäten einzubauen und du hättest schon längst damit fertig sein können! (Ernsthaft, schau mal auf den Kalender, innerhalb zwei Wochen muss sowas doch drin sein...)
 Also schau, dass du das Zeug jetzt endlich mal fertig kriegst!

Ich erwarte von dir, dass du das jetzt heute noch fertig machst und in Zukunft regelmäßig an deinen Aufgaben arbeitest.

**Comment by geht** [comment]
auch nochmal der Hinweis auf die Beschreibung des Milestones
"Make it possible to connect a mobile device to the editor and send projects."

**Comment by RockItDown** [comment]
Danke,
wird gemacht, Chef.

**Comment by geht** [comment]
ist der milestone fertig?
wenn ja, warum hast du dann immernoch net dein zeugs in den master gepusht und den milestone zugemacht? schau dir gerne nochma #103 an.
und ich hoffe, du arbeitest an deinen anderen aufgaben #108, #122, ...

**Comment by RockItDown** [comment]
also ich habe in verschiedenen Netzwerken sehr unterschiedliche Ergebnisse erhalten und verscuhe den Unterschied herauszufinden, es würde mir weiterhelfen, wenn ihr die neuste Version bei euch auch testen könntet, danke

**Comment by geht** [comment]
1. Jetzt fängst du nach einer weiteren Woche erst an deinen Code zu testen?
2. Nach über drei Wochen! für diesen Milestone hast du ihn noch immer nicht fertig.
3. Jetzt möchtest du, dass wir deinen Code babysitten? Jeder hat was zu tun und wir können uns nicht auch noch alle um deinen Code kümmern.
4. Ich habe dich schon vor über einer woche drum gebeten uns mal eine kompilierte Version vom neuen Player bereitzustellen. Wo ist die?
5. Was heißt "unterschiedliche Ergebnisse"? Teile uns doch bitte mit was du getestet hast, was dabei passieren sollte und was dabei stattdessen herausgekommen ist.
6. Sag uns konkret, was du getestet haben möchtest.
7. Es kann doch nicht sein, dass du immer erst was arbeitest auf Nachfrage! Was soll denn das?

p.s. Keine Sorge, falls mir nochwas einfällt trag ich das hier noch nach...

**Comment by RockItDown** [comment]
1. Nein, ich versuche schon seit einer Woche herrauszufinden, was an den zwei Netzwerekn unterschiedlich war...zum Beispiel lief es garnicht als ich meinen Usb-WifiStick benutzt habe. will aber herausfinden was der Grund war.

2.Ich dachte ja ich sei fertig, aber als ich es dann in einem anderen Netzwerk getestet hatte, ging es nichtmehr...uns seither versuch ich den Fehler zu finden

3.Ihr sollt ihn nicht Babysitten, aber jedes Netzwerk ist unterschiedlich, vielleicht gibt es noch andere Effekte

4.Der Player ist im PlayerOrdner in der Dropbox

5.beim ersten Netzwerk wurde der UDP broadcast gesendet und empfangen, beim anderen Netzwerk, war es zunächst nicht möglich einen Broadcast zu senden, danach habe ich den WlanStick den ich verwendet habe, gegen usbthethering mit meinem handy im selben netzwerk getauscht und plötzlich hat er ihn gesendet, aber das tablet hat ihn nicht erreicht

6.probiert es einfach mal bei euch im heimnetzwerk aus, ob ein gerät erkannt wrd. evtll mit wireshark schaun, was gesendet wird und so, aber das ist nicht wichtig, falls es geht, sagt mir einfach die konfiguration von eurem netzwerk, damit ich weiß wann es geht und wann nicht

7.das problem ist, dass ich mich nur auf nachfrage melde und sonst nur allein rumwerkel, ja ich weiß ich sollt mehr mitteilen

**Comment by geht** [comment]
Ich habe mal folgendes gemacht:
Auf meinem Rechner mit der IP 192.168.123.102 hab ich den Player laufen. Der gibt mir in der Konsole auch aus, dass er als listening ist.

Ich hab grade mal probiert deinen Branch ExperimentalDeviceConnection auszufuehren.
Auf dem Laptop (IP 192.168.123.101) wollte ich den editor ausfuehren. Der Branch kompiliert, fuehrt allerdings nicht aus und gibt mir folgende exception:

![image](https://f.cloud.github.com/assets/882090/2184948/f21cecb2-97ca-11e3-83f8-e9eec884b0e8.png)

Auf dem Screenshot kann man erkennen, dass er durchaus ein device gefunden hat, mit der IP von meinem Rechner, was ja schon mal ganz schoen ist.
Allerdings funktioniert der explizite cast auf DeviceSelectionWindow nicht.
Das scheint daran zu liegen, dass du das window ohne initialisierte komponenten uebergibtst.
Wenn ich das ganze umschreibe, sodass erst initializeComponents() auf dem window aufgerufen wird, kann ich das Programm ausfuehren.
Allerdings bekomme ich dann die Meldung, dass ich kein Geraet ausgewaehlt haette...

![image](https://f.cloud.github.com/assets/882090/2185029/ad0a0d6a-97cc-11e3-9a8d-4dd2d802b56f.png)

![image](https://f.cloud.github.com/assets/882090/2185054/208d88ca-97cd-11e3-99dd-f75d06687bbb.png)

Ergibt diese Abfrage so ueberhaupt Sinn?
Wenn ich es umschreibe, sodass er sich mit meinem Geraet verbinden soll passiert folgendes:

Der Player am PC ist einfach abgeschmiert, er hat sich einfach geschlossen ohne jegliche weitere Ausgabe und soweit ich dass jetzt gesehen habe, hat er auch nicht in irgendeine logfile geschrieben oder so.
Und der Editor am Laptop sagt folgendes:

![image](https://f.cloud.github.com/assets/882090/2185089/e5081850-97cd-11e3-9de8-83f238e9f5c7.png)

Ausnahmedetails:
System.IO.IOException wurde nicht behandelt.
  HResult=-2146232800
  Message=Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
  Source=System
  StackTrace:
       bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
       bei ARdevKit.Controller.Connections.DeviceConnection.DeviceConnectionController.connectTo(Int32 index) in c:\Users\geht\Source\Repos\ARdevKit\Editor\Controller\Connections\DeviceConnection\DeviceConnectionController.cs:Zeile 94.
       bei ARdevKit.DeviceSelectionWindow.connectTo_Click(Object sender, EventArgs e) in c:\Users\geht\Source\Repos\ARdevKit\Editor\DeviceSelectionWindow.cs:Zeile 52.
       bei System.Windows.Forms.Control.OnClick(EventArgs e)
       bei System.Windows.Forms.Button.OnClick(EventArgs e)
       bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       bei System.Windows.Forms.Control.WndProc(Message& m)
       bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
       bei System.Windows.Forms.Button.WndProc(Message& m)
       bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       bei System.Windows.Forms.Application.RunDialog(Form form)
       bei System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
       bei System.Windows.Forms.Form.ShowDialog()
       bei ARdevKit.EditorWindow.tsm_editor_menu_file_connection_Click(Object sender, EventArgs e) in c:\Users\geht\Source\Repos\ARdevKit\Editor\EditorWindow.cs:Zeile 1115.
       bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
       bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
       bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
       bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
       bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
       bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
       bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
       bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
       bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       bei System.Windows.Forms.Control.WndProc(Message& m)
       bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
       bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
       bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       bei System.Windows.Forms.Application.Run(Form mainForm)
       bei ARdevKit.ARdevKitEditor.Main() in c:\Users\geht\Source\Repos\ARdevKit\Editor\ARdevKitEditor.cs:Zeile 21.
       bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       bei System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.Net.Sockets.SocketException
       HResult=-2147467259
       Message=Eine vorhandene Verbindung wurde vom Remotehost geschlossen
       Source=System
       ErrorCode=10054
       NativeErrorCode=10054
       StackTrace:
            bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
            bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
       InnerException: 

Die Verbindung wurde also anscheinend vom Remotehost (muesste in meinem Fall der PC sein) geschlossen. Was auch logisch klingt, da sich der Player ja einfach verabschiedet hatte, da scheint noch der Wurm drinzusein...

Ich hoffe diese Informationen koennen dir ein bisschen weiterhelfen.

**Comment by RockItDown** [comment]
vielen Dank für das Testen, ich hab mir dem Problem schon etwas angenommen und hatte jetzt schon ne Menge von Problemen, aber irgendwie scheinen immer wieder neue aufzutauchen. Im moment, habe ich das Problem, dass die NetworkStream.write() methode nach einer gewissen geschriebenen Menge nichtsmehr in den stream schreibt. Bei kleinen Dateien ist es daher kein Problem, aber bei großen. ich schreibe und lese in chunks, falls jemand schonmal das glecihe Problem hatte, wäre cih dankbar für Hilfe, Danke

**Comment by RockItDown** [comment]
Setting the sendingBuffer, to the Project size seems to solve the Problem in the Sending side, however just a very small amount of data is received by the recieving side, maybe just the last chunk of data written to the stream from writer.

**Comment by RockItDown** [comment]
made code more stable, got rid of popup window uses now internel menue

**Comment by RockItDown** [comment]
183896f905a2ab0104261c061b87977c8262bb46

with Bugfixes 
in adbbc2eba10a135519a2a5608ea7c378f06219dc
and 7474618e47dd5b93ea0c1880cae9f42c79528d29
