### ISSUE TITLE
Milestone Augmentations due

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#107]
Milestone Augmentations due to 14.02.2014 20:00 UTC + 01:00

@cr0ssing those tasks belonging to elementselection and panel

@Firebusa those tasks belonging to export

**Comment by geht** [comment]
@cr0ssing @Firebusa 
how is your progress on this one? Is there merge-able code yet?

**Comment by cr0ssing** [comment]
code is mergable from my side. when merged a new dll will be necessary get it here -> http://www.nrecosite.com/downloads/video_converter_1.0_free.zip

**Comment by ImanuelRichter** [comment]
What is that needed for? because we already use <a href="http://www.aforgenet.com/">AForge</a> which may be able to do the same

**Comment by cr0ssing** [comment]
we use it to create a bitmap thumbnail as a preview for video augmentation. i don't know if aforge kann do that

**Comment by cr0ssing** [comment]
aforge does the same :) changed it so that the additional dll isn't needed anymore.

**Comment by geht** [comment]
this looks done for now, if you disagree you may reopen this issue right away^^
