### ISSUE TITLE
Milestone device debugmode due

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#108]
Milestone device debugmode due to 14.02.2014 20:00 UTC + 01:00

afaik the debug information is being send to stdout, you might wanna try to reroute it.
http://stackoverflow.com/questions/584868/rerouting-stdin-and-stdout-from-c

**Comment by RockItDown** [comment]
7474618e47dd5b93ea0c1880cae9f42c79528d29
