### ISSUE TITLE
/FA11410/ ‘Hilfe’

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#110]
/FA11410/ ‘Hilfe’ zeigt eine Dokumentation über alle Funktionen von ARdevKit an.

**Comment by cr0ssing** [comment]
implemented functionality that the menu item help can open a help file in chm format. added a dummy Documentation.chm to Documentation folder. If this is copied bin/Debug Help can be shown. A real Documentation will be created in the QA Phase...

**Comment by geht** [comment]
interesting to see here is that the help window stays in the foreground...
I can't get back to the editor unless i close or minimize the help... xD
but the basic feature is there, so I'm closing this one for now
