### ISSUE TITLE
/FA20000/ Test

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#116]
/FA20030/ Rückgabe der IDs der erkannten Marker
/FA20040/ Rückgabe von Exceptions, die durch den vom Benutzer erstellten Event-Code geworfen werden
/FA20050/ Rückgabe von Informationen über die Verbindung zum Server
/FA20060/ Rückgabe der an den Server gesendeten Anfragen und Antworten

**Comment by ImanuelRichter** [comment]
Obsolete because we have #21 and #108
