### ISSUE TITLE
Add Video Augmentations

### ISSUE THREAD

**Issue by cr0ssing** [ImanuelRichter/ARdevKit#118]
make it possible to add video files as augmentations to a scene.

information here: http://dev.metaio.com/content-creation/movie/

@Firebusa implement exporting logic

**Comment by cr0ssing** [comment]
added to GUI. TODO: provide proper preview image.

**Comment by cr0ssing** [comment]
implemented preview function

**Comment by cr0ssing** [comment]
about to merge to master add this -> http://www.nrecosite.com/downloads/video_converter_1.0_free.zip <- dll to debug folder

**Comment by geht** [comment]
Is it correct, that currently only *.3G2 videos are supported?

**Comment by cr0ssing** [comment]
yes, only 3g2 videos are supported by the metaio sdk.
