### ISSUE TITLE
Implement classes from ProjecktController

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#12]

**Comment by geht** [comment]
Is there a dedicated ProjectController that is hold by the EditorWindowController? Or does the EditorWindowController hold instances of each Visitor?
Which controller uses those classes?

**Comment by RockItDown** [comment]
I think the EditorWindowController should hold an instance of each visitor. therefore the button press for save and export can be linked to the functions of the visitors. I think an additional controller would not be so beneficial for loose coupling.

**Comment by RockItDown** [comment]
in my version i had to add a "public visit(Project project);" method to the Visitors in order to be consistent with Project.accept(AbstractProjectVisitor visitor);.

**Comment by geht** [comment]
you too, please take Issue #19 to heart if you havn't already. (just reminding...)

**Comment by Lizzard2397** [comment]
cdad7335f710ec1eccfd6dff5ca09133b3ab66a8
closed! Stubs are implemented
