### ISSUE TITLE
Create proper Element initialization

### ISSUE THREAD

**Issue by cr0ssing** [ImanuelRichter/ARdevKit#121]
status-quo: when elements are added with the previewController, the controller has to do individual initialization and setting of properties for each element type. Many typecasts are needed for this -> the method is very long and not easy extensible.

target: provide an interface for the modell classes that is called by the previewController. each model class has its own initialization logic. the previewController can handle all elements as the same and new elements are easier to implement.

**Comment by cr0ssing** [comment]
implemented interface on branch Augmentations. a little testing is needed before merged to master. includes major changes in PreviewController.addPreviewable()

**Comment by geht** [comment]
@cr0ssing how is your progress on this?

**Comment by cr0ssing** [comment]
merged master in branch augmentations. implementation is done. i will make sure it works correct and  doesn't destroy other things and merge it to master then.

**Comment by Bareus** [comment]
don't know, if the thing i'm posting now is correct here, but oh well... :
When adding an augmentation to a scene, no ID is set. I need an ID, if I want to add the customUserEvent i need some kind of ID. 

maybe you must ask @Firebusa to know, how/which ID should be used for an augmentation

**Comment by cr0ssing** [comment]
setting IDs at element initialization now.
since initialization seems to work fine i'll be closing this...
