### ISSUE TITLE
Templates for sourceFile, query etc.

### ISSUE THREAD

**Issue by Bareus** [ImanuelRichter/ARdevKit#133]
@Firebusa can you provide commented templates for a sourceFile and query etc.? 
I will then see, how I can add these to the project, so the user gets an option add custom Templates.

Oh yeah, this also goes to @cr0ssing , since I don't know, how he will make the elementSelection extendable to the user.

**Comment by ImanuelRichter** [comment]
I think taking a look at highcharts <a href="http://www.highcharts.com/demo">demo</a>, <a href="http://www.highcharts.com/docs">documentation</a> and <a href="http://www.highcharts.com/ref">API</a> is much better then writing templates
