### ISSUE TITLE
What is ARdevKit.exe.config?

### ISSUE THREAD

**Issue by Bareus** [ImanuelRichter/ARdevKit#135]
Can someone explain me, why this file is being generated? And if it is ok, to ignore it? I had a problem with merging my branch to the master, because of this. To solve it, I had simply deleted it in my folder, but since it's in my folder again, it will probably make some ruckus again, when I want to merge my branch in the master again later.

**Comment by ImanuelRichter** [comment]
Needed because <a href="http://www.aforgenet.com/">AForge</a> (used for #28) uses dlls which are compiled with .NET 2
