### ISSUE TITLE
editor doesn't play loaded projects anymore?

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#137]
for me the recent master doesn't play loaded projects anymore.
I still can load projects to the editor but the player won't play it.

@Firebusa @cr0ssing @Bareus @Lizzard2397 @RockItDown 
please confirm whether the behavior is the same for you and check the recent changes you have made.

**Comment by geht** [comment]
![image](https://f.cloud.github.com/assets/882090/2229750/9136c3fa-9af4-11e3-8417-37a2f53b1ea9.png)

Also, wenn ich das richtig verstanden habe passiert folgendes.
Ich habe mal ein Projekt geladen und auf Bild testen geklickt. Der Exporter exportiert anscheinend alles in den currentProject ordner aber der TestController uebergibt anscheinend den Projectpfad zur Projektdatei, wo dann zu dem Zeitpunkt eben nur die Projektdatei liegt und nicht die benoetigten assets.
Das Verhalten tritt auch auf, wenn man ein neues Projekt speichert und dann den Test ausfuehrt, also scheinbar jedes Mal sobald der projectPfad gesetzt wurde.

Also @Firebusa bitte check doch mal deinen Testcontroller und den export durch.

**Comment by ImanuelRichter** [comment]
Fixed
