### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#139]
Add LiveSource to the ElementSelectionPanel (export already done).

**Comment by cr0ssing** [comment]
added to ElementSelectionPanel. @Bareus is work for PropertyGrid needed?

**Comment by Bareus** [comment]
probably, but I think it is just some minor tweaks i have to make (like categories etc.). if not... well, i have to look it up first ^^'

**Comment by ImanuelRichter** [comment]
Obsolete: LiveSource can now be handled as DbSource
