### ISSUE TITLE
PropertyGrid

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#144]
@Bareus 
Chart: Variablen , Height/Width und Rotation entfernen!

**Comment by Bareus** [comment]
killed the variable in b327ea8607 (only from propertyGrid!)

@Firebusa the height/width variables are still in use in the exportVisitor class. please look up, if they are necessary. if not, delete them so we can completly kill them from the code :)

**Comment by Lizzard2397** [comment]
It's done.
Charts are now scaleable again. Heigh/Width are again in the property grid
