### ISSUE TITLE
Position Augmentation

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#145]
Position der Augmentation stimmt nicht 1zu1 überein

![screenshot 2014-02-24 10 25 21](https://f.cloud.github.com/assets/6215477/2243913/af3ed232-9d35-11e3-8c26-c5f269c06dde.png)

**Comment by Lizzard2397** [comment]
![screenshot 2014-02-24 10 33 42](https://f.cloud.github.com/assets/6215477/2243975/c704824e-9d36-11e3-8f60-eb5ede22be2b.png)

oberes Bild Trackable größe 100
unteres Bild Trackable größe 60 
beides an selber position allerdings nicht im player!

**Comment by ImanuelRichter** [comment]
Note: if you change something -> something should change
And i think it looks like "zoomed" what probably may be the right thing

**Comment by Lizzard2397** [comment]
Die Größe des trackables  nimmt iwie Einfluss auf die Vektoren hab es fast fertig gefixt :D

**Comment by Lizzard2397** [comment]
3b4e11e33eededc259a4480eecebb6f41753c43d 
fix
