### ISSUE TITLE
Video Augmentation

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#148]
There is no previewPicture when someone add a videoaugmentation to the previewPanel! pls fix this fast, so that i can test this!
![screenshot 2014-02-26 11 01 56](https://f.cloud.github.com/assets/6215477/2268682/5b857c74-9ecd-11e3-853e-877cb4dee93f.png)
@cr0ssing

**Comment by cr0ssing** [comment]
first thing I can say is that this is now defect of the preview creation or the getPreview() method. It has to to be destroyed somewhere later at scaling etc...

**Comment by cr0ssing** [comment]
found bug in PreviewController.scaleIPreviewable(). fix and merged to master.
