### ISSUE TITLE
Infinite loop, when deleting augmentations(image)

### ISSUE THREAD

**Issue by RockItDown** [ImanuelRichter/ARdevKit#150]
Infinite loop, when deleting a picture, setup:
- 3 scenes with markers and pictures, one different each
- deleting picture in first scene, everything fine
- deleting picure in second scene, infinite loop
  ![capturebug infiniteloop](https://f.cloud.github.com/assets/6231914/2312021/ea4b46f0-a2f6-11e3-89a8-93efadf484e2.PNG)

**Comment by Lizzard2397** [comment]
207d87f464b316f66d712e85d5281d74077b9eb8
fix
