### ISSUE TITLE
dragging something, which is not from the SelectionPanel into the PreviewPanel, causing NullReferenceException

### ISSUE THREAD

**Issue by RockItDown** [ImanuelRichter/ARdevKit#151]
tested with, for example files, Tab(from Opera)
![nulldragdrop](https://f.cloud.github.com/assets/6231914/2316766/41ae4196-a33c-11e3-9f63-99cea42857f5.PNG)

**Comment by Lizzard2397** [comment]
c390b1f44b6fe10bab7a3e6f440cd2ffd095b3c8
fix
