### ISSUE TITLE
duplicate with ImageTrackables causing too many Filedialogs to open

### ISSUE THREAD

**Issue by RockItDown** [ImanuelRichter/ARdevKit#152]

**Comment by Lizzard2397** [comment]
what do you mean with this bug?

**Comment by RockItDown** [comment]
if you duplicate a scene with an image trackable and you chose the same image, there is no messagebox so its quite unclear what happens, but its logical and correct not to allow the same picture twice. if you chose another picture however, the one you wanted to chose first is displayed in the previewpanel in the new scene

**Comment by Lizzard2397** [comment]
3c08507ec69a76b80ef55f5e7bddc9a8cce1cae6
fix
