### ISSUE TITLE
chart Editor Bug

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#155]
![screenshot 2014-03-04 14 22 43](https://f.cloud.github.com/assets/6215477/2321256/1edfe746-a3a0-11e3-95a8-a258b613cd05.png)
if you change some statements in the options of a chart you editor saves this in the prototype! this shouldn't be like this.
also if you have two charts with the same option and you change a statement in the first it's also changed in the second! so it's the same option!

**Comment by Bareus** [comment]
fixed in 7a3b82d
