### ISSUE TITLE
Testcases for EditorWindow + TestController

### ISSUE THREAD

**Issue by cr0ssing** [ImanuelRichter/ARdevKit#159]
Implement/Design the Testcases for this classes on unit/UI level. This includes the following TCs from the Pflichtenheft:
TF111**
TF112**
TF113**
TF125**

Infos here: https://github.com/Firebusa/ARdevKit/wiki/Anmerkungen-zum-Testen

**Comment by cr0ssing** [comment]
how is your progress on this? will you be able to finish this in the next few days?

**Comment by Bareus** [comment]
#219 for TF11110

**Comment by Bareus** [comment]
seems like, @Firebusa has made TF1115\* already...

**Comment by Bareus** [comment]
Implemented all /TF111**/ in 1f6250de0b72ea356d9fa28284e3e6cebf8f549b

**Comment by Bareus** [comment]
implemented /TF112**/ in d85fc43c04d430abb08b73aa9f625c439cceb0f9

**Comment by Bareus** [comment]
implemented /TF125**/ in 9189344e47972bd0846aecf56f7a9376051812e3

**Comment by Bareus** [comment]
implemented /TF113**/ besides TF11325 in 4b791209053b755f4ce71b46d8c01ab33c0b351a
reason for TF11325 is, I have no virtual camera and do not know, what actually happens. If someone can explain it for me, I can make a test based on his information

**Comment by Bareus** [comment]
implemented tests for TestController to prove its stability in 992561c8abc8396771dd1d5b35b5ae2b5ff3db7e

**Comment by Bareus** [comment]
oke i have impelmented only some minor unit test for EditorWindow class in 18a969ea73bde3dd346192a1c5a84a275544f664. Only checked methods with parameter and only if they are stable. It doesn't make sense to check the other methods, since most of them are depending on other thinks, so I hope the manual tests I wrote are sufficient for this.
