### ISSUE TITLE
Preperation: Implement methods and attributes in EditorWindowController (Stubs)

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#16]
subissue from Issue #7 Implement EditorWindowController w/o delegated functions

Attention:
The EditorWindow.cs is the EditorWindowController as well as its view! That is because of the autogeneration of the GUI by VisualStudio and .net

Task:
Implement the methods and attributes from the EditorWindowController according to the class diagram and design.
For Preperation do only Stubs.

commit history:
https://github.com/Firebusa/ARdevKit/commit/fad4a8005cc92e5a61a2222095099b64e5b0561f added attributes from the class diagramm to the EditorWindow(Controller), as well as comments.
https://github.com/Firebusa/ARdevKit/commit/ec256f2b45475e9ba8e08689d1a9dc7178a86251 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/de4cef63a2dca99084dbbf06d0fc43271bfc155a cleaned and commented Imanuels code in the EditorWindow.cs
https://github.com/Firebusa/ARdevKit/commit/bc3ade9366df45e48b0061fbb7e92560a6842472 added TODO comments in EditorWindow.
https://github.com/Firebusa/ARdevKit/commit/78ab967d369a5d73341b50dfde3914756a1811e7 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/14c670749af7a70ddc2435c599fcd15546651f79 added (stub) methods to EditorWindow.cs according to the class diagram.
https://github.com/Firebusa/ARdevKit/commit/72e597123b69ce71d6808b2fadf2be138a8829ed added List containing IPreviewables to EditorWindow according to class diagram.
https://github.com/Firebusa/ARdevKit/commit/6e93a2fed9c07603457df1509b8a10cf584eb255 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/c0afb8aa91538071ef4361d48d5d0f43bb7bac24 added subcontroller to EditorWindow.cs according to class diagram. added ElementSelectionController, PreviewController, PropertyController, DeviceConnectionController.
https://github.com/Firebusa/ARdevKit/commit/d7cd613f24a0711917c8c73e2c85612f2d3be0ad added ExportVisitor and SaveVisitor.
https://github.com/Firebusa/ARdevKit/commit/fb5ba37e09b41ce2aa3a1a401387801af2615dd3 added IPreviewable currentElement

commited in branch EditorWindow

merged with master
https://github.com/Firebusa/ARdevKit/commit/23bc92b4299795e32349ebef71c8451aea5b27db Merge branch 'EditorWindow'
https://github.com/Firebusa/ARdevKit/commit/e646b17d2f2045ce131fc14ac817d1ba5df0d440 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/3b9ba4193547d24d12795400ff17b4dd2c8106c1 had to change several getter and setter methods from public to internal due to the implementation of the model

**Comment by geht** [comment]
according to the class diagram the TestController isn't hold by the EditorWindowController.
Is that correct? I think the EditorWindowController needs a reference to the TestController to start tests and debugs

**Comment by Bareus** [comment]
It is possible that the TestController and the DebugController is not in this project, but in the other (C++) project with the player, since it needs the metaioSDK (which we still don't know, if it is possible to make a C# wrapper, if we get the license for it).

**Comment by geht** [comment]
according to the class diagramm there are still the TestController and DebugController classes in the Editor project plus i really do need to start tests and debugs someday...
I hope that maybe Firebusa can shed some light on this. I don't want to close this issue quite yet withouth knowing if i have to add an attribute for the TestController (and/or DebugController) or not.

**Comment by geht** [comment]
according to Firebusa the TestController is now static, that means it will not be an attribute of the EditorWindow

**Comment by geht** [comment]
according to RockItDown (Issue #12) this class also needs one of each visitor

**Comment by geht** [comment]
afaik all stubs are now commited in branch EditorWindow

**Comment by geht** [comment]
still depends on completion of #14 and #20

**Comment by geht** [comment]
merged with master
