### ISSUE TITLE
Testcases for ExportVisitor + Player Scene Interpretation

### ISSUE THREAD

**Issue by cr0ssing** [ImanuelRichter/ARdevKit#160]
Implement/Design the Testcases for this class and for the Component of the Player on unit/UI level. This includes the following TCs from the Pflichtenheft:
TF20010
TF20020
TF20070
TF20100
Create testcases that cover scenarios for a variety of scenes to be interpreted by the player

@Firebusa @RockItDown for time reasons one of you should do this because the other have less experience with the enviroment/C++

Infos here: https://github.com/Firebusa/ARdevKit/wiki/Anmerkungen-zum-Testen

**Comment by cr0ssing** [comment]
How is your progress on this? There are no commits from you for tests. Test implementation should be finished by friday!

**Comment by RockItDown** [comment]
i encounter problem with the c++ part, but with info from immanuel i should be able to finish it today
