### ISSUE TITLE
Testcases for DeviceConnectionController + Player Project Import and Debug

### ISSUE THREAD

**Issue by cr0ssing** [ImanuelRichter/ARdevKit#161]
Implement/Design the Testcases for this class and for the components of the Player on unit/UI level. This includes the following TCs from the Pflichtenheft:
TF11150
TF11151
TF20030
TF20040
TF20050
TF20060
TF20080
TF20090

@Firebusa @RockItDown for time reasons one of you should do this because the other have less experience with the enviroment/C++

Infos here: https://github.com/Firebusa/ARdevKit/wiki/Anmerkungen-zum-Testen

**Comment by ImanuelRichter** [comment]
I think TF20050 and TF20060 can be removed cause this depends on the query defined by the user

**Comment by cr0ssing** [comment]
I agree on that. Instead please make on testcase with user defined output messages
