### ISSUE TITLE
Testcases for CustomUserEvent + PropertyController

### ISSUE THREAD

**Issue by cr0ssing** [ImanuelRichter/ARdevKit#163]
Implement/Design the Testcases for this class on unit/UI level. This includes the following TCs from the Pflichtenheft:
TF123**

Infos here: https://github.com/Firebusa/ARdevKit/wiki/Anmerkungen-zum-Testen

**Comment by cr0ssing** [comment]
implemented some property controller ui tests. if you want to execute them place these files in C:\ https://www.dropbox.com/s/y2jht97oc7fid5n/testfiles.zip

**Comment by geht** [comment]
![image](https://f.cloud.github.com/assets/882090/2384416/64802eca-a90c-11e3-8f04-0388ceaf687e.png)

tests fail for me because the recording can't seem to find my "Lokaler Datenträger C:"
the EmptyOptionsTest doesn't finish at all...

Seems to be kinda difficult to test with this whole UI stuff...

**Comment by cr0ssing** [comment]
if you have a C Drive it works if you increase the size of the filedialog so that "Lokaler Datenträger C:" is visible
![screen](https://f.cloud.github.com/assets/742564/2386405/a0927f66-a92b-11e3-8568-e8fa202e8741.png)

**Comment by geht** [comment]
okay, i'll try it out (but shouldn't it work regardless of how big my window is?)

**Comment by cr0ssing** [comment]
it should but I had this problem too today. I guess Codes UI Tests have its boundaries....

**Comment by geht** [comment]
maybe it works better with putting the path in the addressbar rather than clicking on it

**Comment by geht** [comment]
still doesn't work for me with bigger window, it still does not find c:\ and therefore won't add the augmentations correctly...

**Comment by cr0ssing** [comment]
typing in the path should work better as I already type in the filename. I will adjust this testcases when I finished all my testcases.

**Comment by cr0ssing** [comment]
8a3a735ad2 implemented unit test for TextForm

**Comment by cr0ssing** [comment]
all tests are implemented and work so I close this for now
