### ISSUE TITLE
Testcases for PreviewController + TextEditorForm

### ISSUE THREAD

**Issue by cr0ssing** [ImanuelRichter/ARdevKit#164]
Implement/Design the Testcases for this classes on unit/UI level. This includes the following TCs from the Pflichtenheft:
TF122**

Infos here: https://github.com/Firebusa/ARdevKit/wiki/Anmerkungen-zum-Testen

includes:
#171
#172
#173
#174
#175
#176
#177
#178
#180

**Comment by geht** [comment]
closing, for details please look at

#171 PreviewController unit tests
#172 PreviewController UI tests
#173 TextEditorForm unit tests
#174 TextEditorForm UI tests
#175 TF12210
#176 TF12220
#177 TF12230
#178 TF12240
#180 TF12250
