### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#193]
Try to start debug and send project afterwards -> device wont be listed

**Comment by RockItDown** [comment]
the device was not listed at which time exactly? 
with debugconnection still active, sending a project is not possible and is therefore not find in the List.
if this is not the problem, the problem might be an OK too much is sent by the Player,
so the protocoll does not work properly, but in this case the player should reset its sockets eitherway.

**Comment by ImanuelRichter** [comment]
It happens when you start debug before you send a project...

**Comment by RockItDown** [comment]
9c2b694f45d3781f191658e0ddce9ab38dcb5e92
