### ISSUE TITLE
/TF20070/ Laden eines Projektes

### ISSUE THREAD

**Issue by RockItDown** [ImanuelRichter/ARdevKit#199]
Vorbedingungen:
 vorhandenes Projekt auf dem Gerät im richtigen Ordner
Nachbedingungen:
 Projekt muss geladen werden
 Szene muss korrekt angezeigt und abgespielt werden
Testdaten:
 vorbereitetes Projekt

**Comment by RockItDown** [comment]
@cr0ssing ich hätte eine Frage: bezieht sich das nur auf den Player oder auch auf den Editor, also jetzt im Testview, als auch im normalen Betrieb.

**Comment by cr0ssing** [comment]
es bezieht sich auf den player. es geht dadrum ob er mit übergebenen projekt dateien richtig umgeht. überprüf am besten auch was passiert wenn man "kaputte" projekte in den player einliest.
