### ISSUE TITLE
saved project isn't loaded correctly when...

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#202]
Following problem:

When you create a project and add stuff (which need assets) like a chart or an image augmentation, save it and close the program without exporting or testing the project you can't load the project properly again because the needed assets didn't exported to the project directory

**Comment by RockItDown** [comment]
This was fixed by Immanuel, by always Exporting when saving 53e7cf63fc59989790c1f0ab4011e21227e94bbc
