### ISSUE TITLE
bug in export

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#208]
when creating a project and exporting it following problems occur:

when using a chart with a source attached to it a wrong query path gets passed to the chart.js (for example $.getScript("Assets/chart1/fileSource3_query.js", function() ) instead of $.getScript("Assets/chart1/query.js", function() ))
when testing the project the query file can't be loaded then, because it's named query.js and not fileSourceX_query.js

for the charts the absolute! path to the tmp folder gets exported, for the other augmentations the absolute! path to the assets folder gets exported.

saving absolute paths make it impossible to load the exported project on another computer (which is why we have problems sharing a test project now)

Guys this is important!
I stated another problem that got to do with this in #202 

@RockItDown @Firebusa if possible please resolve this, because right now we can't share saved projects!

**Comment by RockItDown** [comment]
as far as i can see this Problem has already been solved by Immanuel with 53e7cf63fc59989790c1f0ab4011e21227e94bbc. but I'm not quite sure what you exactly mean by this Problem

**Comment by ImanuelRichter** [comment]
Is there a test for this bug?

**Comment by ImanuelRichter** [comment]
I think this is fixed so i close this issue... if there is a test for it and it fails -> reopen this
