### ISSUE TITLE
unhandled SerializationException

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#209]
when loading a file which is no proper serialization this happens:

![image](https://f.cloud.github.com/assets/882090/2397202/7cfaf324-a9e6-11e3-9e89-b21b57763c2e.png)

![image](https://f.cloud.github.com/assets/882090/2397200/6aec9dae-a9e6-11e3-8435-5ee8b4d082dc.png)

**Comment by RockItDown** [comment]
149dcb0353f02bd4f1a3c762dfa499fd657c8826
