### ISSUE TITLE
unhandled FileNotFoundException

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#210]
when the customUserEventTemplate.txt is missing and you try to "Oeffne AREL Script"

![image](https://f.cloud.github.com/assets/882090/2397430/27748b78-a9ea-11e3-8024-1a3439e07f23.png)

![image](https://f.cloud.github.com/assets/882090/2397456/8b26854a-a9ea-11e3-8527-10c639d125ae.png)

**Comment by Bareus** [comment]
fixed 531f60929777893d650cdad1ac2c5a5d7c384588
