### ISSUE TITLE
unhandled ArgumentException

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#215]
unhandled ArgumentException when trying to remove the last remaining scene:

![image](https://f.cloud.github.com/assets/882090/2407691/0246b4be-aa91-11e3-8899-1dc6702afd3f.png)

![image](https://f.cloud.github.com/assets/882090/2407692/06c82c98-aa91-11e3-8333-87e0bd325072.png)

**Comment by Lizzard2397** [comment]
ea9ed0cfcf83cfd8575302aa9cf87f16ec0c734a
fix 
an if request was missing
