### ISSUE TITLE
speichern unter wird aufgerufen, obwohl es schon gespeichert ist, falls man zuvor speichern unter Dialog abgebrochen hat

### ISSUE THREAD

**Issue by RockItDown** [ImanuelRichter/ARdevKit#218]
1.speichern(normal) führt zu speichern unter Dialog | korrekt
2.speichern unter(abbrechen) | korrekt
3.speichern(normal) | bug

**Comment by geht** [comment]
the speichern unter resets the projectPath, this is why it does a speichern unter in step 3

closing this for now...
I can't seem to fix it without major code re-factoring or causing other problems...
and it doesn't seem to cause other problems for now

reopen this if important
