### ISSUE TITLE
Save As, or saving after the projectPath has been changed, causes someFiles not be included in the Assets Folder 

### ISSUE THREAD

**Issue by RockItDown** [ImanuelRichter/ARdevKit#220]
the files missing are options queries and datafiles for charts and the Custom user event files along with the resFiles
in short, every File, which is unique to this project.

to test this bug you may use 
Export_Project_FullIDMarker
Export_Project_FullPictureMarker
Export_Project_FullImageTrackable

**Comment by ImanuelRichter** [comment]
Added oldProjectPath to project so files can be copied from there
