### ISSUE TITLE
scaleBitmap Bug

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#224]
![scalebitmapbug](https://f.cloud.github.com/assets/6215477/2419807/e657c67e-ab64-11e3-8466-f970f900a219.jpg)
if you load a imageAugmentation in the box and resize the trackable size to 1 you'll get this exception because the size of the Picturebox is to big

**Comment by geht** [comment]
dirty workaround: when the scaling might get too big, the original image is returned
https://github.com/Firebusa/ARdevKit/commit/bccd46de31d0a0876780743bc68727252999ab25
