### ISSUE TITLE
Load a video without using a virtual camera

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#28]
Make it possible to pass a path to a video to the player and use it as source.

**Comment by ImanuelRichter** [comment]
trying to use http://docs.opencv.org/modules/highgui/doc/reading_and_writing_images_and_video.html

**Comment by ImanuelRichter** [comment]
Gonna close this issue for the first release (not working).

**Comment by ImanuelRichter** [comment]
Passing a video to the player is possible now using <a href="http://www.aforgenet.com/">AForge</a> to extract every single frame into a temporary folder.
This path is passed to the player which loads every single frame like it does with images.
The update interval is based on de fps from the original video. This value is passed as well.

**Comment by geht** [comment]
I tried to load the example video but the player just displays a black image
![image](https://f.cloud.github.com/assets/882090/2193819/f3002424-9882-11e3-97a1-7da29c183103.png)

**Comment by ImanuelRichter** [comment]
ARdevKit.exe.config was needed to run because <a href="http://www.aforgenet.com/">AForge</a> uses dlls compiled with .NET 2
