### ISSUE TITLE
Implement the view of PropertyController

### ISSUE THREAD

**Issue by Bareus** [ImanuelRichter/ARdevKit#29]
Like the title says, implement the view of PropertyController.

What should be added:
- PropertyGrid from .net Framework
- add/delete etc. button's to add customUserEvents to an AbstractAugmentation. maybe it can be included in the propertyGrid?

**Comment by Bareus** [comment]
implemented PropertyGrid and merged it to the master. 
There may be a high chance, that my PropertyController is completly unnecessary, because the PropertyGrid makes thinks more easier than tought.
Added "tags" in the Model, so the property in the PropertyGrid actually is shown. 
Still not closed, because I haven't tested if it actually works like intended and I still don't know, how the presentation looks like with the tags.

**Comment by ImanuelRichter** [comment]
Maybe you can use this for some options:
http://bytes.com/topic/c-sharp/answers/238511-combobox-propertygrid

**Comment by Bareus** [comment]
If there is a property which should have a certain way of representation, let me know. I will try to implement it, like you want it to have (best is to make a new issue which should have the Property milestone assign.
