### ISSUE TITLE
Function: public void updatePreviewPanel()

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#40]
subissue from Issue #7 Implement EditorWindowController w/o delegated functions

updatePreviewPanel()
Nutzt den PreviewController, um das PreviewPanel zu aktualisieren, wenn ein IPreviewable hinzugefügt oder Einstellungen im PropertyPanel geändert werden.

**Comment by Lizzard2397** [comment]
f08ba8125b0f736e7d69631fa85a84681c6d4a19
