### ISSUE TITLE
Function: public void updatePropertyPanel(IPreviewable selectedElement)

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#41]
subissue from Issue #7 Implement EditorWindowController w/o delegated functions

updatePropertyPanel(selectedElement : IPreviewable)
Nutzt den PropertyController, um die Einstellungen zum übergebenen IPreviewable anzuseigen, wenn ein IPreviewable vom Benutzer ausgewählt wird.

**Comment by Bareus** [comment]
Look at issue #24 please.
