### ISSUE TITLE
Function: public void updateSceneSelectionPanel()

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#42]
subissue from Issue #7 Implement EditorWindowController w/o delegated functions

updateSceneSelectionPanel()
Updated das SceneSelectionPanel, falls ein neues Trackable hinzugefügt oder ein bereits existierendes durch ein neues ersetzt wird.

**Comment by Lizzard2397** [comment]
a4c24396ba459300a289d27c896a63595a1b8151
