### ISSUE TITLE
Implement Save/Load Controller

### ISSUE THREAD

**Issue by RockItDown** [ImanuelRichter/ARdevKit#56]
The Save Controller need not to be designed as a visitor, because project holds all relevant data, only the project must be serialized, because its serializes all collection alongside with it.
Shall we still stick with a SaveVisitor?

**Comment by ImanuelRichter** [comment]
if it is not needed and better to do it without a visitor do it

**Comment by RockItDown** [comment]
was implemented in static SaveLoadController with commit  45bebb4512c11aa4c50c422183bb82073de26976
