### ISSUE TITLE
Implement EditorWindowController w/o delegated functions

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#7]
Attention:
The EditorWindow.cs is the EditorWindowController as well as its view! That is because of the autogeneration of the GUI by VisualStudio and .net

Task:
Implement EditorWindowController according to class diagram and design.

Subissues:
open:
#30 Function: public void addDevice()
#38 Function: public void sendToDevice()
#43 Function: public void updateStatusBar()

closed:
#16 Preperation: Implement methods and attributes in EditorWindowController (Stubs)
#40 Function: public void updatePreviewPanel()
#42 Function: public void updateSceneSelectionPanel()
#31 Function: public void createNewProject(String name)
#32 Function: public void exportProject()
#33 Function: public void loadProject()
#34 Function: public void openDebugWindow()
#35 Function: public void openTestWindow()
#36 Function: public void registerElements()
#37 Function: public void saveProject()
#39 Function: public void updateElementSelectionPanel()
#41 Function: public void updatePropertyPanel(IPreviewable selectedElement)
#44 Function: private void addCategory(SceneElementCategory category)

commit History:
https://github.com/Firebusa/ARdevKit/commit/fad4a8005cc92e5a61a2222095099b64e5b0561f added attributes from the class diagramm to the EditorWindow(Controller), as well as comments.
https://github.com/Firebusa/ARdevKit/commit/ec256f2b45475e9ba8e08689d1a9dc7178a86251 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/de4cef63a2dca99084dbbf06d0fc43271bfc155a cleaned and commented Imanuels code in the EditorWindow.cs
https://github.com/Firebusa/ARdevKit/commit/bc3ade9366df45e48b0061fbb7e92560a6842472 added TODO comments in EditorWindow.
https://github.com/Firebusa/ARdevKit/commit/78ab967d369a5d73341b50dfde3914756a1811e7 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/14c670749af7a70ddc2435c599fcd15546651f79 added (stub) methods to EditorWindow.cs according to the class diagram.
https://github.com/Firebusa/ARdevKit/commit/72e597123b69ce71d6808b2fadf2be138a8829ed added List containing IPreviewables to EditorWindow according to class diagram.
https://github.com/Firebusa/ARdevKit/commit/6e93a2fed9c07603457df1509b8a10cf584eb255 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/c0afb8aa91538071ef4361d48d5d0f43bb7bac24 added subcontroller to EditorWindow.cs according to class diagram. added ElementSelectionController, PreviewController, PropertyController, DeviceConnectionController.
https://github.com/Firebusa/ARdevKit/commit/d7cd613f24a0711917c8c73e2c85612f2d3be0ad added ExportVisitor and SaveVisitor.
https://github.com/Firebusa/ARdevKit/commit/70b9de88beafb7386d21dca2e9b2517ed63df987 "i need a getter & a setter for PreviewPanel" in EditorWindow.designer.cs
https://github.com/Firebusa/ARdevKit/commit/fb5ba37e09b41ce2aa3a1a401387801af2615dd3 added IPreviewable currentElement
https://github.com/Firebusa/ARdevKit/commit/23bc92b4299795e32349ebef71c8451aea5b27db Merge branch 'EditorWindow'
https://github.com/Firebusa/ARdevKit/commit/e646b17d2f2045ce131fc14ac817d1ba5df0d440 Merge branch 'master' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/3b9ba4193547d24d12795400ff17b4dd2c8106c1 had to change several getter and setter methods from public to internal due to the implementation of the model
https://github.com/Firebusa/ARdevKit/commit/f08ba8125b0f736e7d69631fa85a84681c6d4a19 Add the method UpdatePreviewPanel
https://github.com/Firebusa/ARdevKit/commit/a4c24396ba459300a289d27c896a63595a1b8151 fix SceneSelectionPanel
https://github.com/Firebusa/ARdevKit/commit/afa88ae69e298b43c063dd190bd6a83024b9fad3 modified constructor
https://github.com/Firebusa/ARdevKit/commit/03b234777d9f5a77e9690f8cd33b415604858026 addec constructor stub to DeviceConnectionController
https://github.com/Firebusa/ARdevKit/commit/492c8d3361c7fbeb6c53349d1c77e150f99e2893 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/31ed679a24e5996c6132f57e3b50154be47e9365 added initializing of the attributes to the constructor
https://github.com/Firebusa/ARdevKit/commit/8e1327ad748651bda9646f9c2aed9fd72cb507df reorganized code
https://github.com/Firebusa/ARdevKit/commit/97c6ae395d12c6345a429b8e5eb7ed0b6a26a04e corrected errors in initializing block
https://github.com/Firebusa/ARdevKit/commit/99f6cfc50b21c014dc2977faf7743f5109f4d10f changed initializing again...
https://github.com/Firebusa/ARdevKit/commit/d1acf6824d0cba49a0f3757a4fce4163b46c804b added updatePanels()
https://github.com/Firebusa/ARdevKit/commit/cb04316688451cd53d068aa87b4d8b8927d4ff83 added click event for the "Neu" menu
https://github.com/Firebusa/ARdevKit/commit/a8db5fd5ebe43df4bcb6c12a0c078355ade1138d added save file dialog, as well as click event for "Speichern" and "Speichern unter"
https://github.com/Firebusa/ARdevKit/commit/216429ed7f8f65836fc03f5df98101810ce74d5f Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/31a72edcf936c8a5699bd622bf97eb536c088a05 added getter and setter for propertygrid
https://github.com/Firebusa/ARdevKit/commit/4fea0d3f7cb9da85ebc7b06f8fe2288b7b872f20 reorganized some code
https://github.com/Firebusa/ARdevKit/commit/f770610e74e16c26b2e4f7e4be0a96b55ce57359 changed a condition, lizzard wanted this...
https://github.com/Firebusa/ARdevKit/commit/e5c192da4e69c4cd832073575b9cea0b4e733e88 added private void clearControllers()
https://github.com/Firebusa/ARdevKit/commit/0d292f2cc62237381792fe846346e8e5087cae9a modified updateElementSelectionPanel so that initialize empty project works properly
https://github.com/Firebusa/ARdevKit/commit/3497273e45f4e239780b6159b581564842112c6b Merge branch 'EditorWindow' of https://github.com/Firebusa/ARdevKit.git
https://github.com/Firebusa/ARdevKit/commit/5ec9aa765b4e325efa3e7d666c517befc3ea5ecd changed public void updateElementSelectionPanel()
https://github.com/Firebusa/ARdevKit/commit/c0c2cb835c0b22355c7a825f640b2746bb867ea5 implemented createNewProject(String name)
https://github.com/Firebusa/ARdevKit/commit/15c28ce57c93558c0b761c7142984fbdab4f5c83 implemented save method
https://github.com/Firebusa/ARdevKit/commit/13ba84b291b69aca8245c76e21f2432636e19639 changed file extenstion
https://github.com/Firebusa/ARdevKit/commit/3a6ebcd6158696388a79df152f6648735eeb7633 changed save method & implemented load method
https://github.com/Firebusa/ARdevKit/commit/3a6ebcd6158696388a79df152f6648735eeb7633 changed save method & implemented load method
https://github.com/Firebusa/ARdevKit/commit/cdf3154d7540dcc0583daef0a2d9a35523a64bef still not finished with export
https://github.com/Firebusa/ARdevKit/commit/589417b01dbbedfe13f40971632d24d6bdfd8b2f still still not finished with export
https://github.com/Firebusa/ARdevKit/commit/f6c43f84e418f7990de05868b80906d9ea4156ee still a little bug with loading...
https://github.com/Firebusa/ARdevKit/commit/4d23fef24e8763e071bd5fdbb30abac8adc64132 fixed loadProject()
https://github.com/Firebusa/ARdevKit/commit/b33b73b3e9152c2940c03e4f7d3f97dc5125620c Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/380aa297627a5747889490768bedd8d90e59c9aa fixed ElementSelectionController
https://github.com/Firebusa/ARdevKit/commit/017a845e1e574d8516932240cef66c950246332b Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/4fb7d64beee25f851a04db0068f828db62683469 changed save method
https://github.com/Firebusa/ARdevKit/commit/dd5506e988ffc7704c21f1d8c92e09a224483b1e tweaked save method a little bit
https://github.com/Firebusa/ARdevKit/commit/c2d0b88bb3c98bb63f2858914a6b76c146d7b044 implemented exportProject()
https://github.com/Firebusa/ARdevKit/commit/f52f8b2b3aed9df058994ef70dbd2f4e00517ce0 added messagebox to export
https://github.com/Firebusa/ARdevKit/commit/cf681e843bae7e92cd4706ee250e4405d1c9db6b added save question before exitting
https://github.com/Firebusa/ARdevKit/commit/d847b1e6c12d1219e87f98ab938d5a39154a7340 deactivated some (still not functional) buttons
https://github.com/Firebusa/ARdevKit/commit/add4c6b21673d7cac34e131c7ab5542128fd4800 added info messagebox
https://github.com/Firebusa/ARdevKit/commit/e035f2cfc896f0c63252560dfcc76b84f20d905b flagged and commented some obsolete methods
https://github.com/Firebusa/ARdevKit/commit/59040e03e5ca8657039f99e2d092c3291c935e43 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/83fec19b47a48e033d4607cc00a6c438291d6609 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/bb49c91b3865a90a4760f7ee7ceab3070e7c2022 added getter for ElementSelectionController
https://github.com/Firebusa/ARdevKit/commit/860b8b4b6e8c14d784a29e6f2edd657803d2f729 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/f6863ccaf8492d82cb97c1291aed250b4114c058 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/0e20e281b095cb9aa3405f7cd7eb7993932eec75 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/10bde1b45ff1d1c267a4091eebd94f0eb6ec46ab Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/a556c8800328c6eb6a64e3e8e0c56316bf1c779c Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/be924536cb554e64289ae3be6eaff382365c7988 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/2867be766f817cb4a0f79d40f239d14bbc64a276 Merge branch 'master'
https://github.com/Firebusa/ARdevKit/commit/9067d4a1bb3a25a63e5cf573ddfb762669b28f1d Merge branch 'master'

**Comment by geht** [comment]
Attention everyone!
Each subcontroller that is hold by my controller gets this one as a reference. So make sure you implement the constructors of your controllers in the way that i can pass on this controller.

Example:
If i want to instanciate an ElementSelectionController it should work for me like this:
myController = new ElementSelectionController(this);

I hope you understand what i mean^^
You need a reference to the main controller to get the parts of the GUI that you have to update, as well as the data you need from the model.

please leave a comment here which GUI elements you need a getter and setter for.
For example if some needs a getter and/or setter for the panel pnl_editor_selection say so and i will insert the getter and setter. (i don't want every GUI element to be accessable from the very beginning)

Guys, this is as important for you as it is for me, so feel free to comment on this!
@Firebusa @Lizzard2397 @Bareus @cr0ssing @RockItDown

**Comment by Lizzard2397** [comment]
okay 
i need a getter & a setter for PreviewPanel

**Comment by Bareus** [comment]
It is possible that my controller (PropertyController) don't need a reference of the EditorWindowController. This is because the method "updatePropertyPanel(selectedElement : IPreviewable )" might be unnecessary. 
The PropertyGrid (.net Framework) access the selected element directly to read all readable attributes and update itself, if an attribute is been set.

**Comment by Lizzard2397** [comment]
getter & setter for PreviewPanel is implemented by me comes with next commit (i hope that i can merge soon with master)

**Comment by geht** [comment]
@Bareus what getter and setter do you need now?

**Comment by Bareus** [comment]
The only thing my controller needs is a referenz of the current selected element (which must be an from an abstractAugmentation), but currently it get's this via parameter in the method. The rest of the parameter ist user-generated and should just be delegated to my methods, which shouldn't be a problem. (You could say, my controller can be declared as static even tough it isn't :) )

**Comment by geht** [comment]
added currentElement (forgot it before...). It is still only on the EditorWindow branch though...
