### ISSUE TITLE
Implement PreviewController

### ISSUE THREAD

**Issue by ImanuelRichter** [ImanuelRichter/ARdevKit#8]

**Comment by Lizzard2397** [comment]
2 problems: 

first how should it work if we remove an Trackable from the Panel? 
1. remove trackable with all subelements!?
2. can't remove trackable if there are subelements!?

please vote!

second Problem:
how can i link the pictureBox of the Panel with the appropiated element?
example: if i click on the picture box i want know the trackable for which this picturebox is.
Robin has a similar thing in his selectionpanel please answer how did you done this. ty.

**Comment by Lizzard2397** [comment]
Problem with design of PreviewController:
changed Methodheader:
public void addPreviewable(IPreviewable currentTrackable, Vector3D v) <- for Trackables
public void addPreviewable(IPreviewable currentElement, IPreviewable overElement) <- for Augmentation & Source
public void removePreviewable(PictureBox p, IPreviewable prev) <- for all

**Comment by geht** [comment]
you too, please take Issue #19 to heart if you havn't already.

**Comment by ImanuelRichter** [comment]
One solution for the linking problem might be to use a Dictionary
http://msdn.microsoft.com/de-de/library/xfhwa508(v=vs.110).aspx

maybe
http://msdn.microsoft.com/de-de/library/system.windows.forms.control.bindingcontext(v=vs.110).aspx
or
http://msdn.microsoft.com/de-de/library/system.windows.forms.control.databindings(v=vs.110).aspx
could be used as well

**Comment by Lizzard2397** [comment]
ty i've found a solution for my problem with the binding of a objekt to the pictureBox. 
PictureBox has a Tag, which you can use to bind a Objekt to this pictureBox.
Picturebox.Tag = currentElement; is to bind this objekt
Picutrebox.Tag is to call the element.

also i will implement the remove method to delete all subelements.

**Comment by Lizzard2397** [comment]
ebb33f9387bd9a3f04d2c37fe9c1ea91ea77a1b1
latest update.
all implemented without updatePreviewPanel (this doesn't make any sense)
i musst test it.
NOT CLOSED!

**Comment by Lizzard2397** [comment]
close ISSUE! finally! 4a1c538bbab13f1274a32823e4b98dd6b12b4c4f

**Comment by geht** [comment]
When I want to instanciiate the PreviewController i get a neat little exception, because you add a null trackable to the trackable list...
![image](https://f.cloud.github.com/assets/882090/1940736/5315dcdc-7f7e-11e3-8464-776396e84e90.png)

**Comment by Lizzard2397** [comment]
for the preRelease we do it so! :D then we can change it when we would do it other way
