### ISSUE TITLE
rescale Augmentations through the propertyGrid

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#81]
use the funktion updateScale() in previewController!

**Comment by Bareus** [comment]
i have added an event in the propertyController, which will be excecuted when a property in the propertyGrid is changed. i also changed the method updateScale() from private to public to get access to it.

some problems with the scaling vector: i think the range of the scaling vector is (0, 100]. 1 is the normal size (we defined, like, a picture has an initial max width/height of 200px or so). 2 is (possibly) double of this size and so on. 
I'm not 100% sure, if it's correct like this, but at least this is, how it is generated in the metaio creator.

**Comment by Lizzard2397** [comment]
bugs/mistakes are fixed in the current master

**Comment by Bareus** [comment]
it is now possible to recale an augmentation
