### ISSUE TITLE
weird stuff happens when screen size is set to negative values

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#90]

**Comment by ImanuelRichter** [comment]
What happens exactly? What do you think should happen?

**Comment by geht** [comment]
some kind of exception...
this issue is basically a reminder for myself, so that i don't forget to fix this^^

> What do you think should happen?

negative values don't make sense for a screen resolution, i just have to adapt my code a little^^

**Comment by geht** [comment]
https://github.com/Firebusa/ARdevKit/commit/2dac6ffe65f4a8996d59993d76d11dd8bb2fa621 changed the screensize to unsigned values
