### ISSUE TITLE
shall the screen size be serialized?

### ISSUE THREAD

**Issue by geht** [ImanuelRichter/ARdevKit#91]
question @Firebusa @cr0ssing @Bareus @Lizzard2397 @RockItDown 

shall i make the screen size serializable so that it can be stored in the project file?

**Comment by ImanuelRichter** [comment]
i think that would be nice and sensible

**Comment by geht** [comment]
https://github.com/Firebusa/ARdevKit/commit/0a60d37a744f46597ed7c5c54317c5080645d08a moved screensize attribute from editorwindow to project and made the screensize saveable
