### ISSUE TITLE
add EventHandler to PropertyGrid

### ISSUE THREAD

**Issue by Lizzard2397** [ImanuelRichter/ARdevKit#94]
by Augmentation, if Picture (ImageAugmention) or Options(Path) == is set to null => remove this augmentation

by Source if Querry(Path) is set to null QuerryButton disablen!
                 if Querry(Path) is set != null (and is bevor null) QuerryButton enablen!
                 if Data(Path) (FileSource) is set to null remove Source!

ty

**Comment by Bareus** [comment]
implemented in 4d823d2aad . changed it, that, if picture/image/option/data path has been set to null, it will restore the value.
